language: node_js
node_js:
- '4.2'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libcairo2-dev
    - libopencv-dev
    - libjpeg8-dev
    - libpng12-dev
    - libwebp-dev
    - libtiff4-dev
    - libexif-dev
    - libgsf-1-dev
    - libblas-dev
    - liblcms2-dev
    - libxml2-dev
    - libpango1.0-dev
    - build-essential
    - unicode-data
    - automake
    - gobject-introspection
    - gtk-doc-tools
    - libglib2.0-dev
    - swig
script:
- OUT_DIR=`pwd` TARGET=travis VERSION=`git describe --tags` ./build.sh
deploy:
  provider: heroku
  api_key:
    secure: EgnopX+NU76bGBCb7Jv+1FzJrGWsZUw6aEELkEpK7crGThCgvo0jG/17ULEeMFnO30kQwX/Qlg9SWRVGB4h6ySM+75lA705q/TiaJg4KLfS2WWJpZFy1xpVeXPqofUsMPdiUUBULZayLwaKqhdX3mXs6MtELgQvSIfebAn9/eAjZ4+Rc7HfAx/VR4cPeARLyNCvN0iNy3wW3LhWPuCtuVlSOGt0uK6w1hvk6egizARyQ7YFzmqxOUJdnccYrgNtDuyuAmVQmRhH3MN92rH2DLdjWrnFlfoJAgWi3M2HxnKgNtGfqpuckDjkdK4JVZXeGvRM5d0cxXh1yE82yTkz7nHfzYIjSdtU0XbAPH3cRf0uPHg0HUzlSEZ5UoWonyabUdr7s0XM6F2WPLndzCMKhAQD0F0ndnGaOtd1UFGlctNZCw0MEfyoFvNF2sndyaqnVIwF7ILxR8vDujcs4rW5YvckhP/Aez4okDMwOQmIu59JKyfshE/laQGAelqKPi18Rj3rMbiIXLld8+b+ZaggdEJwC/edHy9PO6qoUb9S2oTBqMZk9F+Zx2hfv1+m300Eg+XJLnL8HadyYc/9oj/gdaUEi3OM9u524GruZH3Hc+CcFiu+yNgjSTOc3WTvAWSO4hK89ydKxMAlawf7JNvEB5JufIBvWasqYnL9cWs6Qfao=
  app: imgflo-dependencies14
  on:
    repo: jonnor/heroku-buildpack-vips
    tags: true
  run:
  - TARGET=heroku VERSION=`git describe --tags` ./build.sh
env:
  global:
  - secure: q+THbNxe3jtnYis4/m7VF7pE80nO5kzwVzydZ4WTIilv/W5yrpaCQUIw+WjPGkyLUHmLotZud852gqFPJhE55Q8oI843a/0VCrYjnUob33SQDz7+U5plCvrYmJVsuMpIJUvVTKpr8CTvNy4EUxoYGvlbA1VDfyQgkiRGU484pg5ggjYs4Kc/myVf/cmmWTXGxvwxIgLZeTprv+KO6PWLetkxZ1UP3QLrX9lLmrA/nZo6AGAFcTZLk+POjYzIiRQcntdRewj03Co1G+rL31N3/H6EU1rPRT7aelmhNstSRASJE+POcB8wTKrOTVNvDzV6/dgiFC2MWWZdu+83L1JLm2FzWxKhnYT6B81QO8ZIQ2ltwRVuNe8YuWUp45GQvuw0Da1ZQE8UlfAqw035jNxfIk/xTxK0ygclCf2HeWO6fJPzwNrnUQbijoLVD4dFWmDemkoUAPyLixc7klLRFGEhgPRPyDWnokrAE8H4WU7Jf1zOtW6Cn1FuothLPvYrqFqUXJ3sBMYCpFpKTP8ziufw+RPY52i1R/FzveLQPOhndYk1SJg2v95VdnNkxKl80pqYkq/258nOHNsMYxHTEnjONTM+e/ooLWUkyEg+hm29Mk5i03XDNGuzDqBu02FLktVTOQKzSHuTtTZB3EHx6lvXmwYaQ5s2qmfHWmN6eWevRYM=
  - secure: aq5DlSC5hzukJC4Xi8lD7FTkIbHRiK6NiM9RSsRlB2diiVuuzEiKz8LguaOR5rG360yT37i14hEBOetQMYgkaE8DWpkPdK96ajpSvJ8kytiA9gp3zfytN9SnY53IylKoPiykswIdoFbKXibngbwO7evV8+CTp3GeAKd4zkXOczlb99Sbxl9JdCdaeSVitMEX4p0WsSH73CMBLpF2FsM0+S9j0bTCz16ZUoz5/QwMUZ7Qq8aO4dYfGUeR9wR8FYLGyfwo7owZuo7xCcEm/X1fcalCJe+h5DUCDwJOs/9HZ39qHpU1H1eDSgBzmI6+s1WM2YsVKoPjYVfig24BmDKDYXFEnnPzd8CJafNYPfpgEtYvCBmMtwhfdpMA84l30J/0P4mA/lsiDEUmH9wfTsNhz+RQ25Ym8ou25pal70G89RQNTWiPnqB2LZQ2wQ/WkUH5sAEQr62jwAjigoUR283MopWNrqwMjWVlpOPuyc79F5nCy8KqeKMBi+d0yABR3whu1Z0LXgETSCsleU5rOkc/rg6R0ISW3u76m5q+hoIQXcFsEuPIuhaTwWob9yLDkEp2iw88cjMZ+olvXmmGvh8pP9q8VU0sSXL8amzN1mgtDRoYnghkNuOdk0DN1O3N3i3NlYWWkwV109qy0l6+VqqQt+IEY988pwIw7nVC0/PkDaA=
  - secure: bfORmf60jI6wM4uOvUj18B7fPQre8LZw+GrJvRAE/Jz9rvYXclcDxbxrcJV5a8CzdNTKz8TfJCQqIahp4T9edodvjxFEZ5dHywkz+stb9dC8slQ++tAwZ9nTFH4o6Hic7IMPGdcSgMZzCnoinxCttsvqyX2poBuPqNcHpqToszRIUab66GewWUtMhbMVUZ637UuooUOqFe8BbffZy3TBNitIW+0adxymyVXrnfM3DBNO9mWm7XApuirmIe5QIV1KI/gwR05+sth9Z9OS3s9/btgNIG6ZXq3QiJgsTAvHH24a/y0YjJd17bx/hDnCUrMn6CVsZwpcc/bckF3iQLcI/qRcK0sKHFI5CdSOwMUwWnXQPiBhbL4vfEZDBQNgyG9q5j2T3yfOuSbTlpHuaDh8iShSZs7RmTjWOUkkrgrUopdMbLX08Zk718nq+e+W4wsxt/hPhcd98GRd70eoiFPB5ZwiJEfGEhCHquNZcaNbLvIsk7zTHzvdfIeDwPzN0U76kK7huFmafvlxMNjiL1AJDZVxyamtU9ySRgR9G5W0otYzABPYGSsA+DC/JOtb2w8n2L+nhwhBhxd8EGF0IpkHNtwWrV8NFdQ5xqScLJs4KS1UH0jQEHObsAuIPwEknubJtxqAy7hDKQUMc95SAJJYHEY2x5/w9UvO02K57QshO58=
