language: node_js
node_js:
- '4.2'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - imagemagick
    - libmagickcore-dev
    - libcairo2-dev
    - libgif-dev
    - libopencv-dev
    - libjpeg8-dev
    - libpng12-dev
    - libwebp-dev
    - libtiff4-dev
    - libexif-dev
    - libgsf-1-dev
    - libblas-dev
    - libgsl0-dev
    - libfftw3-dev
    - liblcms2-dev
    - libxml2-dev
    - libpango1.0-dev
    - build-essential
    - unicode-data
    - automake
    - gobject-introspection
    - gtk-doc-tools
    - libglib2.0-dev
    - swig
script:
- TARGET=travis VERSION=`git describe --tags` ./build.sh
deploy:
  provider: heroku
  api_key:
    secure: EgnopX+NU76bGBCb7Jv+1FzJrGWsZUw6aEELkEpK7crGThCgvo0jG/17ULEeMFnO30kQwX/Qlg9SWRVGB4h6ySM+75lA705q/TiaJg4KLfS2WWJpZFy1xpVeXPqofUsMPdiUUBULZayLwaKqhdX3mXs6MtELgQvSIfebAn9/eAjZ4+Rc7HfAx/VR4cPeARLyNCvN0iNy3wW3LhWPuCtuVlSOGt0uK6w1hvk6egizARyQ7YFzmqxOUJdnccYrgNtDuyuAmVQmRhH3MN92rH2DLdjWrnFlfoJAgWi3M2HxnKgNtGfqpuckDjkdK4JVZXeGvRM5d0cxXh1yE82yTkz7nHfzYIjSdtU0XbAPH3cRf0uPHg0HUzlSEZ5UoWonyabUdr7s0XM6F2WPLndzCMKhAQD0F0ndnGaOtd1UFGlctNZCw0MEfyoFvNF2sndyaqnVIwF7ILxR8vDujcs4rW5YvckhP/Aez4okDMwOQmIu59JKyfshE/laQGAelqKPi18Rj3rMbiIXLld8+b+ZaggdEJwC/edHy9PO6qoUb9S2oTBqMZk9F+Zx2hfv1+m300Eg+XJLnL8HadyYc/9oj/gdaUEi3OM9u524GruZH3Hc+CcFiu+yNgjSTOc3WTvAWSO4hK89ydKxMAlawf7JNvEB5JufIBvWasqYnL9cWs6Qfao=
  app: imgflo-dependencies14
  on:
    repo: jonnor/heroku-buildpack-vips
